######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG+= crypto

# Input
HEADERS += CustomTextEdit.hh SmallDialogs.hh ChatDialog.hh FileShareManager.hh
SOURCES += main.cc CustomTextEdit.cc SmallDialogs.cc ChatDialog.cc FileShareManager.cc
